service:
  name: answer4me

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  # Example with LAMBDA-PROXY integration
  # Invoking locally:
  # sls webpack invoke -f hello
  phonein:
    handler: callresponder.phonein
    events:
      - http:
          method: post
          path: phone
          integration: lambda
          response:
            headers:
              Content-Type: "'text/xml'"
            template: $input.path('$')

  checkgetrecording:
    handler: checkgetrecording.phonein