service:
  name: answer4me

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

custom:
  DynamoDBTableName: answer4me-call-log

functions:
  # Example with LAMBDA-PROXY integration
  # Invoking locally:
  # sls webpack invoke -f hello
  phonein:
    handler: callresponder.phonein
    events:
      - http:
          method: post
          path: phone
          integration: lambda
          response:
            headers:
              Content-Type: "'text/xml'"
            template: $input.path('$')

  checkgetrecording:
    handler: checkgetrecording.phonein

resources:
  Resources:
      DynamoDBTable:
        Type: "AWS::DynamoDB::Table"
        Properties:
          TableName: ${self:custom.DynamoDBTableName}
          AttributeDefinitions:
            - AttributeName: callid
              AttributeType: S
          KeySchema:
            - AttributeName: callid
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: "1"
            WriteCapacityUnits: "1"
